#!/usr/bin/env bash
# Check if a domain name is provided as an argument

function dig_it(){

    if [ $# -eq 2 ]; then
        domain="$1"
        subdomain="$2"

        dig "$subdomain.$domain" | grep -A1 "ANSWER SECTION" | awk '/www/ || /lb-01/ || /web-01/ || /web-02/ {print "The sub domain", $1, "is a", $4, "record", "pointing to", $5}'
    else
        domain="$1"

        # List of subdomains to check
        subdomains=(
            "www"
            "lb-01"
            "web-01"
            "web-02"
        )

        # Loop through each subdomain and dig it
        for subdomain in "${subdomains[@]}"; do
            dig "$subdomain.$domain" | grep -A1 "ANSWER SECTION" | awk '/www/ || /lb-01/ || /web-01/ || /web-02/ {print "The sub domain", $1, "is a", $4, "record", "pointing to", $5}'
        done
    fi
}

# Check if domain argument is provided
if [ $# -lt 1 ]; then
    echo "Usage: $0 <domain> [<subdomain>]"
    exit 1
fi

# Call the function
dig_it "$@"
