#!/bin/env/bash
#configuring new ubuntu server

# Update package repositories
sudo apt update

# Install Nginx
sudo apt install -y nginx

# Configure Nginx to listen on port 80 and serve a specific webpage content
cat << EOF | sudo tee /etc/nginx/sites-available/default > /dev/null
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        internal;
        default_type text/html;
        echo "404 Page Not Found";
    }
}
EOF

# Create a custom 404 error page
sudo bash -c 'echo "404 Page Not Found" > /var/www/html/404.html'

# Restart Nginx to apply changes
sudo service nginx restart

# Verify Nginx status
sudo servuce nginx status
