#!/usr/bin/env bash
# Install Nginx package

sudo apt-get update
sudo apt-get install -y nginx

# Create custom 404 page with desired content
sudo mkdir -p /usr/share/nginx/html
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html >/dev/null

# Configure Nginx to use the custom 404 page
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/custom_404
sudo sed -i '/error_page/c\    error_page 404 /404.html;' /etc/nginx/sites-available/custom_404
sudo sed -i '/location \/ {/a\        location = /404.html {\n            internal;\n            root /usr/share/nginx/html;\n            index index.html;\n            return 404 "Ceci n'\''est pas une page\n";\n        }\n' /etc/nginx/sites-available/custom_404

# Enable the custom 404 site
sudo ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/

# Test Nginx configuration and restart Nginx
sudo nginx -t && sudo systemctl restart nginx
