#!/usr/bin/env bash
# SSH into web-01 and web-02 servers

# Use sed to add the custom header inside the http block in nginx.conf
sudo sed -i '/http {/a \    add_header X-Served-By "527246-web-01";' /etc/nginx/nginx.conf

# Reload Nginx to apply the changes
sudo service nginx restart


# Use sed to add the custom header inside the http block in nginx.conf
sudo sed -i '/http {/a \    add_header X-Served-By "527246-web-02";' /etc/nginx/nginx.conf

# Reload Nginx to apply the changes
sudo service nginx restart