#!/usr/bin/env bash
# This will be ping an IP address

ip_address=$1

if [ -z "$ip_address" ]
then
        echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
        ping -c 5 "$ip_address"
fi
