#!/usr/bin/env bash

# Print "Best School" 20 times

count=1

while [ "$count" -le 20 ]

do
    case $count in
        4)
            echo "$count"
            echo "bad luck in China"
            ;;
        9)
            echo "$count"
            echo "bad luck in Japan"
            ;;
        17)
            echo "$count"
            echo "bad luck in Italy"
            ;;

        *)
            echo "$count"
            ;;

    esac
    ((count++))
done
